### PR TITLE
feat: add a lru cache group by tag

### PR DESCRIPTION
**Pull request by JettHu**
Add a TaggedCache impl base on `cachetools.LRUCache`. The purpose is to limit the number of caches for different tags.

Cache settings found in config file  `tag_settings.json`.

### CODE REVIEW

**Comment by ltdrdata** [comment]
image

I think it would be good to allow edit of the settings for the LRU Cache here.

**Comment by JettHu** [comment]
> image
> 
> I think it would be good to allow edit of the settings for the LRU Cache here.

Good idea, but I'm not very familiar with the front end, but I can try to change it.

**Comment by JettHu** [comment]
> I think it would be good to allow edit of the settings for the LRU Cache here.

Already implement it.

**Comment by ltdrdata** [comment]
I'll review it later.

**Pull request merged**
